name: Simple CI

on: [push, pull_request]  # Runs on every push and pull request

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   

      - name: Print a message
        run: echo "Hello, GitHub Actions!"
